name: dev_loggerx
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/vignarajj/dev_loggerx
homepage: https://vignaraj.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  dio: ^5.4.0
  http: ^1.2.0
  uuid: ^4.2.1
  intl: ^0.19.0
  animations: ^2.0.11
  share_plus: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.4
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
